apiVersion: "v1"
kind: "Service"
metadata:
  name: "jaxrs-spf4j-demo-ext"
  namespace: "default"
  labels:
    app: "jaxrs-spf4j-demo"
    version: "0.7-SNAPSHOT"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "jaxrs-spf4j-demo"
    version: "0.7-SNAPSHOT"
  type: "LoadBalancer"
  loadBalancerIP: "34.96.112.42"