#beta
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: operator
rules:
- apiGroups: ["ops"]
  resources: ["services"]
  verbs: ["get", "post", "put", "delete"]