apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jaxrs-spf4j-demo
  name: jaxrs-spf4j-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jaxrs-spf4j-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaxrs-spf4j-demo
      name: jaxrs-spf4j-demo
    spec:
      volumes:
        - name: logs-storage
          hostPath:
            path: /var/log/apps/jaxrs-spf4j-demo
            type: DirectoryOrCreate
      containers:
      - image: zolyfarkas/jaxrs-spf4j-demo:0.8-SNAPSHOT
        # IfNotPresent | Always ...
        imagePullPolicy: Always
        name: jaxrs-spf4j-demo
        volumeMounts:
          - name: logs-storage
            mountPath: /var/log
        ports:
        - containerPort: 8080
        - containerPort: 9090
        resources:
          requests:
            cpu: "200m"
            memory: 220Mi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: KUBE_NAME_SPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBE_APP_NAME
            value: jaxrs-spf4j-demo
          - name: KUBE_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        livenessProbe:
             httpGet:
               path: /health/check/local
               port: 8080
             initialDelaySeconds: 10
             periodSeconds: 30
             timeoutSeconds: 5
        readinessProbe:
             httpGet:
               path: /health/ping
               port: 8080
             initialDelaySeconds: 5
             periodSeconds: 15
             timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
