apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: jaxrs-spf4j-demo
    version: 0.5-SNAPSHOT
  name: jaxrs-spf4j-demo
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/jaxrs-spf4j-demo
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: jaxrs-spf4j-demo
      version: 0.5-SNAPSHOT
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jaxrs-spf4j-demo
        version: 0.5-SNAPSHOT
      name: jaxrs-spf4j-demo
    spec:
      containers:
      - image: zolyfarkas/jaxrs-spf4j-demo:0.5-SNAPSHOT
        # IfNotPresent | Always ...
        imagePullPolicy: Always
        name: jaxrs-spf4j-demo
        resources:
          requests:
            cpu: "1"
            memory: 512Mi
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: KUBE_NAME_SPACE
            value: default
          - name: KUBE_APP_NAME
            value: jaxrs-spf4j-demo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
